In [12]:
import numpy as np

# 1D array oluşturma
arr = np.array([1, 2, 3, 4, 5])
print(arr)

# 2D array oluşturma
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [13]:
# 2D array'in transpozunu alma
arr = np.array([[1, 2, 3], [4, 5, 6]])
transposed_arr = arr.T
print(transposed_arr)

[[1 4]
 [2 5]
 [3 6]]


In [14]:
# 2x4 birlerden oluşan array
ones_arr = np.ones((2, 4))
print(ones_arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
# 0'dan 10'a kadar 2'şer artan array
range_arr = np.arange(0, 10, 2)
print(range_arr)

[0 2 4 6 8]


In [16]:
# 0 ile 1 arasında 5 eşit aralıklı değer
linspace_arr = np.linspace(0, 1, 5)
print(linspace_arr)

[0.   0.25 0.5  0.75 1.  ]


In [17]:
# 3x3 rastgele sayılardan oluşan array
random_arr = np.random.rand(3, 3)
print(random_arr)

[[0.06560244 0.54607059 0.07706115]
 [0.63913044 0.91396307 0.35542142]
 [0.77811773 0.96330531 0.34503907]]


In [18]:
# 1D array'i 2D array'e çevirme
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [19]:
# 2D array'den belirli bir elemanı seçme
arr = np.array([[1, 2, 3], [4, 5, 6]])
element = arr[1, 2]  # 2. satır, 3. sütun
print(element)

# Dilimleme
sliced_arr = arr[:, 1:3]  # Tüm satırlar, 2. ve 3. sütunlar
print(sliced_arr)

6
[[2 3]
 [5 6]]


In [20]:
# Array üzerinde matematiksel işlemler
arr = np.array([1, 2, 3, 4])
sum_arr = np.sum(arr)  # Toplam
mean_arr = np.mean(arr)  # Ortalama
max_arr = np.max(arr)  # Maksimum değer

print("Toplam:", sum_arr)
print("Ortalama:", mean_arr)
print("Maksimum:", max_arr)

Toplam: 10
Ortalama: 2.5
Maksimum: 4


In [10]:
# Belirli bir koşula göre array elemanlarını filtreleme
arr = np.array([1, 2, 3, 4, 5])
filtered_arr = arr[arr > 2]
print("Filtrelenmiş Array:", filtered_arr)

Filtrelenmiş Array: [3 4 5]
